apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-elysia-api
  labels:
    app: bun-elysia-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bun-elysia-api
  template:
    metadata:
      labels:
        app: bun-elysia-api
    spec:
      containers:
        - name: bun-elysia-api
          image: your-docker-repo/bun-elysia-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: bun-elysia-api-secrets
            - configMapRef:
                name: bun-elysia-api-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---